### ISSUE TITLE
Compatibility changes from 0.x -> 1.x

### ISSUE THREAD

**Issue by cmungall** [shaypal5/cachier#5]
Hi, I love cachier!

I'm just investigating some things in our stack that appear to be broken with the release of cachier 1.1x: https://github.com/biolink/biolink-api/issues/53

Is there a list of changes for the 1.x series?

**Comment by shaypal5** [comment]
@cmungall 

Hi Chris!

Thank you for your kind words. :)

I had no idea someone was using this package for some serious stuff.
There isn't anything specific I can think about, but I did a major refactoring and restructuring of the code - hence the release as a new major version; it looked possible this would break somethings.

Any hints you can give me to help me track down an issue? I want to make sure it is not a bug, and also document major changes.

Also, generally, recall that since the convention is that major versions (X.0.0) are allowed to make backward compatibility-breaking changes, it worth to bound your dependencies in a way that will only install new minor versions (0.X.0), which by conventions do not break APIs and but make sure you get security and hotfixes.

In Python `requirements.txt` or `setup.py` files this can be achieved by setting `cachier~=0.1.26`. This will make sure that if version 0.1.28 -for example - is found on PyPI it will be used, but not 1.0.0.

Cheers! <3
Shay

**Comment by cmungall** [comment]
Thanks for the tips - yes I was being lazy and not setting a version in requirements.txt

Hmm, looking more closely it doesn't seem to be an API compatibility issue, but perhaps some kind of issue with the distribution on pypi. This is what was reported to me, and I get the same when I try and do a fresh install:

```
(venv) ~/tmp/cachier-test $ pyvenv venv
(venv) ~/tmp/cachier-test $ source venv/bin/activate
(venv) ~/tmp/cachier-test $ pip install cachier
Collecting cachier
  Using cached cachier-1.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    warning: no files found matching '.isort.cfg'
    warning: no files found matching '.pylintrc'    warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    
    Installed /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-ewdszt29/cachier/.eggs/pytest_cov-2.4.0-py3.5.egg
    Searching for coverage
    Reading https://pypi.python.org/simple/coverage/
    Best match: coverage 4.4b1
    Downloading https://pypi.python.org/packages/e3/f1/288295356ad9d15dfba10bb05c105ea648399869fd72c3ef444f78a3aef4/coverage-4.4b1.tar.gz#md5=d3800a5a0ed2bca1
f7200a9641d35242
    Processing coverage-4.4b1.tar.gz
    Writing /var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/easy_install-0825vdav/coverage-4.4b1/setup.cfg
    Running coverage-4.4b1/setup.py -q bdist_egg --dist-dir /var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/easy_install-0825vdav/coverage-4.4b1/egg-dist-tmp
-7aly6b5x
    warning: no previously-included files found matching 'ci/appveyor.token'
    no previously-included directories found matching 'doc/_build'
    no previously-included directories found matching 'tests/eggsrc/build'
    no previously-included directories found matching 'tests/eggsrc/dist'
    no previously-included directories found matching 'tests/eggsrc/*.egg-info'
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    creating /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-ewdszt29/cachier/.eggs/coverage-4.4b1-py3.5-macosx-10.11-x86_64.egg
    Extracting coverage-4.4b1-py3.5-macosx-10.11-x86_64.egg to /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-ewdszt29/cachier/.eggs
    
    Installed /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-ewdszt29/cachier/.eggs/coverage-4.4b1-py3.5-macosx-10.11-x86_64.egg
    Searching for pytest
    Best match: pytest cov-2.4.0
    Downloading https://pypi.python.org/packages/00/c0/2bfd1fcdb9d407b8ac8185b1cb5ff458105c6b207a9a7f0e13032de9828f/pytest-cov-2.4.0.tar.gz#md5=2fda09677d232a
cc99ec1b3c5831e33f
    Processing pytest-cov-2.4.0.tar.gz
    Writing /var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/easy_install-9z4e_3sy/pytest-cov-2.4.0/setup.cfg                                                 
    Running pytest-cov-2.4.0/setup.py -q bdist_egg --dist-dir /var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/easy_install-9z4e_3sy/pytest-cov-2.4.0/egg-dist-tmp-lrtgh323
    warning: no files found matching '.isort.cfg'
    warning: no files found matching '.pylintrc'
    warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    
    Installed /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-ewdszt29/cachier/.eggs/pytest_cov-2.4.0-py3.5.egg
    Searching for coverage
    Reading https://pypi.python.org/simple/coverage/
    Best match: coverage 4.4b1
    Downloading https://pypi.python.org/packages/e3/f1/288295356ad9d15dfba10bb05c105ea648399869fd72c3ef444f78a3aef4/coverage-4.4b1.tar.gz#md5=d3800a5a0ed2bca1f7200a9641d35242
    Processing coverage-4.4b1.tar.gz
    Writing /var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/easy_install-0825vdav/coverage-4.4b1/setup.cfg
    Running coverage-4.4b1/setup.py -q bdist_egg --dist-dir /var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/easy_install-0825vdav/coverage-4.4b1/egg-dist-tmp-7aly6b5x
    warning: no previously-included files found matching 'ci/appveyor.token'
    no previously-included directories found matching 'doc/_build'
    no previously-included directories found matching 'tests/eggsrc/build'
    no previously-included directories found matching 'tests/eggsrc/dist'
    no previously-included directories found matching 'tests/eggsrc/*.egg-info'
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    creating /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-ewdszt29/cachier/.eggs/coverage-4.4b1-py3.5-macosx-10.11-x86_64.egg
    Extracting coverage-4.4b1-py3.5-macosx-10.11-x86_64.egg to /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-ewdszt29/cachier/.eggs
    
    Installed /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-ewdszt29/cachier/.eggs/coverage-4.4b1-py3.5-macosx-10.11-x86_64.egg
    Searching for pytest
    Best match: pytest cov-2.4.0
    Downloading https://pypi.python.org/packages/00/c0/2bfd1fcdb9d407b8ac8185b1cb5ff458105c6b207a9a7f0e13032de9828f/pytest-cov-2.4.0.tar.gz#md5=2fda09677d232acc99ec1b3c5831e33f
    Processing pytest-cov-2.4.0.tar.gz
    Writing /var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/easy_install-9z4e_3sy/pytest-cov-2.4.0/setup.cfg
    Running pytest-cov-2.4.0/setup.py -q bdist_egg --dist-dir /var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/easy_install-9z4e_3sy/pytest-cov-2.4.0/egg-dist-tmp-lrtgh323
    warning: no files found matching '.isort.cfg'
    warning: no files found matching '.pylintrc'
    warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    removing '/private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-ewdszt29/cachier/.eggs/pytest_cov-2.4.0-py3.5.egg' (and everything under it)
    creating /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-ewdszt29/cachier/.eggs/pytest_cov-2.4.0-py3.5.egg
    Extracting pytest_cov-2.4.0-py3.5.egg to /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-ewdszt29/cachier/.eggs
    
    Installed /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-ewdszt29/cachier/.eggs/pytest_cov-2.4.0-py3.5.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-ewdszt29/cachier/setup.py", line 60, in <module>
        'Intended Audience :: Developers',
      File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/cjm/tmp/cachier-test/venv/lib/python3.5/site-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/cjm/tmp/cachier-test/venv/lib/python3.5/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/cjm/tmp/cachier-test/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 829, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'pytest' distribution was not found and is required by the application
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-ewdszt29/cachier/
```

looks like some issue with the coverage package?

**Comment by shaypal5** [comment]
OK, I think I figured out what the problem is.

I accidentally uploaded `v1.1.5` from my computer but never pushed the tag to github, so there was no matching source distribution package here for PyPI to get.

Can you try again and tell me if this is resolved?

**Comment by cmungall** [comment]
```
Collecting cachier
  Using cached cachier-1.1.6.tar.gz
    Complete output from command python setup.py egg_info:
    warning: no files found matching '.isort.cfg'
    warning: no files found matching '.pylintrc'
    warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    
    Installed /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-u6lqoz9j/cachier/.eggs/pytest_cov-2.4.0-py3.5.egg
    Searching for coverage
    Reading https://pypi.python.org/simple/coverage/
    Best match: coverage 4.4b1
    Downloading https://pypi.python.org/packages/e3/f1/288295356ad9d15dfba10bb05c105ea648399869fd72c3ef444f78a3aef4/coverage-4.4b1.tar.gz#md5=d3800a5a0ed2bca1f7200a9641d35242
    Processing coverage-4.4b1.tar.gz
    Writing /var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/easy_install-ziqfcxha/coverage-4.4b1/setup.cfg
    Running coverage-4.4b1/setup.py -q bdist_egg --dist-dir /var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/easy_install-ziqfcxha/coverage-4.4b1/egg-dist-tmp-fovpfr1s
    warning: no previously-included files found matching 'ci/appveyor.token'
    no previously-included directories found matching 'doc/_build'
    no previously-included directories found matching 'tests/eggsrc/build'
    no previously-included directories found matching 'tests/eggsrc/dist'
    no previously-included directories found matching 'tests/eggsrc/*.egg-info'
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    creating /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-u6lqoz9j/cachier/.eggs/coverage-4.4b1-py3.5-macosx-10.11-x86_64.egg
    Extracting coverage-4.4b1-py3.5-macosx-10.11-x86_64.egg to /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-u6lqoz9j/cachier/.eggs
    
    Installed /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-u6lqoz9j/cachier/.eggs/coverage-4.4b1-py3.5-macosx-10.11-x86_64.egg
    Searching for pytest
    Best match: pytest cov-2.4.0
    Downloading https://pypi.python.org/packages/00/c0/2bfd1fcdb9d407b8ac8185b1cb5ff458105c6b207a9a7f0e13032de9828f/pytest-cov-2.4.0.tar.gz#md5=2fda09677d232acc99ec1b3c5831e33f
    Processing pytest-cov-2.4.0.tar.gz
    Writing /var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/easy_install-_fytc7fj/pytest-cov-2.4.0/setup.cfg
    Running pytest-cov-2.4.0/setup.py -q bdist_egg --dist-dir /var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/easy_install-_fytc7fj/pytest-cov-2.4.0/egg-dist-tmp-r807rzra
    warning: no files found matching '.isort.cfg'
    warning: no files found matching '.pylintrc'
    warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    removing '/private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-u6lqoz9j/cachier/.eggs/pytest_cov-2.4.0-py3.5.egg' (and everything under it)
    creating /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-u6lqoz9j/cachier/.eggs/pytest_cov-2.4.0-py3.5.egg
    Extracting pytest_cov-2.4.0-py3.5.egg to /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-u6lqoz9j/cachier/.eggs
    
    Installed /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-u6lqoz9j/cachier/.eggs/pytest_cov-2.4.0-py3.5.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-u6lqoz9j/cachier/setup.py", line 60, in <module>
        'Intended Audience :: Developers',
      File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/cjm/tmp/cachier-test/venv/lib/python3.5/site-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/cjm/tmp/cachier-test/venv/lib/python3.5/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/cjm/tmp/cachier-test/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 829, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'pytest' distribution was not found and is required by the application
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-build-u6lqoz9j/cachier/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Note it complains about pytest this time.

A workaround:

```
(venv) ~/tmp/cachier-test $ pip install pytest
Collecting pytest
  Using cached pytest-3.0.7-py2.py3-none-any.whl
Collecting py>=1.4.29 (from pytest)
  Using cached py-1.4.33-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./venv/lib/python3.5/site-packages (from pytest)
Installing collected packages: py, pytest
Successfully installed py-1.4.33 pytest-3.0.7
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(venv) ~/tmp/cachier-test $ pip install cachier 
Collecting cachier
  Using cached cachier-1.1.6.tar.gz
Collecting watchdog (from cachier)
Collecting argh>=0.24.1 (from watchdog->cachier)
  Using cached argh-0.26.2-py2.py3-none-any.whl
Collecting PyYAML>=3.10 (from watchdog->cachier)
Collecting pathtools>=0.1.1 (from watchdog->cachier)
Installing collected packages: argh, PyYAML, pathtools, watchdog, cachier
  Running setup.py install for cachier ... done
Successfully installed PyYAML-3.12 argh-0.26.2 cachier-1.1.6 pathtools-0.1.2 watchdog-0.8.3
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by shaypal5** [comment]
@cmungall 

Ok, I think I accidentally listed pytest as a requirement (additionally to it being a test requirement).

Can you uninstall pytest` and try installing `cachier` again for `1.1.8`? It shouldn't depend on pytest...

**Comment by cmungall** [comment]
Success! Many thanks for the prompt fix!

**Comment by shaypal5** [comment]
Sure! Thank you for helping me squash a bug!
